### ISSUE TITLE
正确配置后无法启动

### ISSUE THREAD

**Issue by Michaelwucoc** [FrexCheat/koishi-plugin-github-webhook-lite#1]
![image](https://github.com/user-attachments/assets/fc5c36c5-604e-4377-92c7-adbc2d60c3bb)

**Comment by FrexCheat** [comment]
可以试试看把  `path`  选项的内容改一下？这可能是 `schema` 在这个版本的 bug。如果这样做还是无法启动，请及时回复我。

**Comment by Michaelwucoc** [comment]
![image](https://github.com/user-attachments/assets/80841bb2-a966-45d8-9382-57944761bd54)

![image](https://github.com/user-attachments/assets/6954842f-1021-4d3f-85e9-9fd25cd29b55)


配置都设置了 但是没收到信息

**Comment by Michaelwucoc** [comment]
OK我输入订阅指令后解决了!
